---
- name: Bootstrap web app platform
  hosts: all
  roles:
  - docker
  - consul
  - nomad
  - dhparam
  - self-signed-certificate
  - acme-account
  - clean-stuck-jobs
  - docker-system-prune
  - firewall-rules
  - vouch
  - nginx
  - acme-issuance
  - nginx
