---
#
# Deploys various maintenance batch jobs that don't fit anywhere else
#
- name: Loop over jobs
  ansible.builtin.include_tasks: run-single-job.yml
  loop: "{{ query('ansible.builtin.fileglob', '*.nomad') }}"
