---
#
# Schedules a daily backup of Docker volumes, MySQL databases, and HashiCorp products to AWS S3
#
- name: Check if backup configuration has been loaded in Consul
  ansible.builtin.uri:
    follow_redirects: none
    force: true
    return_content: true
    unix_socket: /var/opt/nomad/run/consul.sock
    use_netrc: false
    use_proxy: false
    validate_certs: false
    headers:
      X-Consul-Token: "{{ ansible_facts['consul_token'] }}"
    method: GET
    url: http://localhost/v1/kv/backup/config
    status_code:
    - 200
  register: backup_config
  ignore_errors: true

- name: Check for required keys in configuration
  ansible.builtin.fail:
    msg: Backup configuration has been loaded in Consul but is missing some required parameters. Check to make sure MYSQLDUMP_SCOPE, DOCKER_VOLUMES, AWS_ROLE_ARN, and AWS_S3_LOCATION are all present in the map.
  when: >-
    backup_config.status == 200 and (
      ("MYSQLDUMP_SCOPE" not in (backup_config.json.0.Value | b64decode | from_json))
      or ("DOCKER_VOLUMES" not in (backup_config.json.0.Value | b64decode | from_json))
      or ("AWS_ROLE_ARN" not in (backup_config.json.0.Value | b64decode | from_json))
      or ("AWS_S3_LOCATION" not in (backup_config.json.0.Value | b64decode | from_json))
    )

- name: Submit backup job
  when: backup_config.status == 200
  block:

  - name: Generate job submission JSON
    ansible.builtin.command:
      argv:
      - nomad
      - job
      - run
      - -no-color
      - -output
      - -var
      - region={{ region }}
      - -var
      - datacenter={{ datacenter }}
      - "-"
      stdin: "{{ lookup('ansible.builtin.file', './backup.nomad') }}"
    register: nomad_job_json
    changed_when: false

  - name: Submit job to Nomad
    ansible.builtin.uri:
      follow_redirects: none
      force: true
      use_netrc: false
      use_proxy: false
      validate_certs: false
      return_content: true
      headers:
        X-Nomad-Token: "{{ ansible_facts['nomad_token'] }}"
      body: "{{ nomad_job_json.stdout }}"
      body_format: json
      method: POST
      url: http://127.0.0.1:4646/v1/jobs
