---
#
# Issue a certificate from Let's Encrypt (or another ACME service)
# https://github.com/acmesh-official/acme.sh
#
- name: Check to see if http-01 challenge passes from controller's perspective
  ansible.builtin.uri:
    follow_redirects: none
    force: true
    use_netrc: false
    use_proxy: false
    validate_certs: false
    method: GET
    return_content: true
    url: http://{{ fully_qualified_domain_name }}/.well-known/acme-challenge/ansible-test
    status_code:
    - 200
    timeout: 5
  delegate_to: 127.0.0.1
  ignore_errors: true
  register: acme_challenge_test

- name: Check if a volume is already created for {{ acme_server }}
  ansible.builtin.uri:
    follow_redirects: none
    force: true
    unix_socket: /var/run/docker.sock
    use_netrc: false
    use_proxy: false
    validate_certs: false
    method: GET
    return_content: true
    url: http://localhost/v1.43/volumes/acme-certificate-{{ acme_server }}
    status_code:
    - 200
    - 404
  register: acme_certificate_volume
  when: not (acme_challenge_test is failed)

- name: Check if a certificate was already issued from {{ acme_server }}
  ansible.builtin.stat:
    path: "{{ acme_certificate_volume.json.Mountpoint }}/fullchain.pem"
  when: acme_certificate_volume.status == 200 and not (acme_challenge_test is failed)
  register: server_cert

- name: Request certificate issuance
  when: not (acme_challenge_test is failed) and (acme_certificate_volume.status == 404 or not server_cert.stat.exists)
  block:

  - name: Retrieve ACME account thumbprint from Consul
    ansible.builtin.uri:
      follow_redirects: none
      force: true
      return_content: true
      unix_socket: /var/opt/nomad/run/consul.sock
      use_netrc: false
      use_proxy: false
      validate_certs: false
      headers:
        X-Consul-Token: "{{ ansible_facts['consul_token'] }}"
      method: GET
      url: http://localhost/v1/kv/acme/{{ acme_server }}-thumbprint
    register: acme_account_thumbprint_consul

  - name: Fail if nginx did not return the expected challenge response
    ansible.builtin.fail:
      msg: Nginx did not return the expected response for the ACME http-01 challenge. Issuance would not be successful.
    when: acme_challenge_test.status != 200 or acme_challenge_test.content != "ansible-test."+(acme_account_thumbprint_consul.json.0.Value | b64decode)

  - name: Prompt for Cloudflare account API token
    ansible.builtin.pause:
      prompt: Please enter the account API token to use with Cloudflare to complete ACME dns-01 challenges
    register: cloudflare_account_api_token

  - name: Prompt for Cloudflare account ID
    ansible.builtin.pause:
      prompt: Please enter the Cloudflare account ID that contains the zones needed to complete ACME dns-01 challenges
    register: cloudflare_account_id

  - name: Verify Cloudflare account API token validity
    ansible.builtin.uri:
      follow_redirects: none
      force: true
      return_content: true
      use_netrc: false
      use_proxy: false
      validate_certs: true
      headers:
        Authorization: "Bearer {{ cloudflare_account_api_token.user_input }}"
      method: GET
      url: https://api.cloudflare.com/client/v4/accounts/{{ cloudflare_account_id.user_input }}/tokens/verify
    delegate_to: 127.0.0.1

  - name: Process additional_certificate_sans
    when:  additional_certificate_sans is defined
    ansible.builtin.set_fact:
      additional_certificate_sans: "{{additional_certificate_sans | map('regex_replace','^','--domain ') |  map('regex_replace','$',' --dns dns_he') | join(' ') | split(' ')}}"
  
  - name: Issue a certificate from {{ acme_server }} - this will take a few minutes, be patient, drink some water
    vars:
      flags:
      - docker
      - run
      - --pull
      - always
      - --rm
      - --network
      - host
      - --read-only
      - --rm
      - --mount
      - type=volume,source=acme-account-{{ acme_server }},destination=/acme.sh/
      - --mount
      - type=volume,source=acme-certificate-{{ acme_server }},destination=/certificate/
      - --env
      - CF_Token={{ cloudflare_account_api_token.user_input }}
      - --env
      - CF_Account_ID={{ cloudflare_account_id.user_input }}
      - neilpang/acme.sh
      - --issue
      - --server
      - "{{ acme_server }}"
      - --domain
      - "{{ fully_qualified_domain_name }}"
      - --stateless
      - --domain
      - "*.{{ datacenter }}.robojackets.net"
      - --dns
      - dns_cf
      - --domain
      - "*.robojackets.org"
      - --dns
      - dns_cf
      - --keylength
      - ec-384
      - --cert-file
      - /certificate/cert.pem
      - --key-file
      - /certificate/key.pem
      - --ca-file
      - /certificate/ca.pem
      - --fullchain-file
      - /certificate/fullchain.pem
      - --ocsp-must-staple
      - --ecc
    ansible.builtin.command:
      argv: "{{flags + (additional_certificate_sans | default([]))}}"

- name: Check if a volume is created for {{ acme_server }}
  ansible.builtin.uri:
    follow_redirects: none
    force: true
    unix_socket: /var/run/docker.sock
    use_netrc: false
    use_proxy: false
    validate_certs: false
    method: GET
    return_content: true
    url: http://localhost/v1.43/volumes/acme-certificate-{{ acme_server }}
    status_code:
    - 200
    - 404
  register: acme_certificate_volume
  when: not (acme_challenge_test is failed)

- name: Check if a certificate was already issued from {{ acme_server }}
  ansible.builtin.stat:
    path: "{{ acme_certificate_volume.json.Mountpoint }}/fullchain.pem"
  when: acme_certificate_volume.status == 200 and not (acme_challenge_test is failed)
  register: server_cert

- name: Manage renewal job
  when: acme_certificate_volume.status == 200 and server_cert.stat.exists
  block:

  - name: Generate renewal job JSON
    ansible.builtin.command:
      argv:
      - nomad
      - job
      - run
      - -no-color
      - -output
      - -var
      - region={{ region }}
      - -var
      - datacenter={{ datacenter }}
      - -var
      - acme-server={{ acme_server }}
      - "-"
      stdin: "{{ lookup('ansible.builtin.file', './acme-renew.nomad') }}"
    register: nomad_job_json
    changed_when: false

  - name: Submit renewal job to Nomad
    ansible.builtin.uri:
      follow_redirects: none
      force: true
      use_netrc: false
      use_proxy: false
      validate_certs: false
      return_content: true
      headers:
        X-Nomad-Token: "{{ ansible_facts['nomad_token'] }}"
      body: "{{ nomad_job_json.stdout }}"
      body_format: json
      method: POST
      url: http://127.0.0.1:4646/v1/jobs

  - name: Force launch the job
    ansible.builtin.uri:
      follow_redirects: none
      force: true
      use_netrc: false
      use_proxy: false
      validate_certs: false
      return_content: true
      headers:
        X-Nomad-Token: "{{ ansible_facts['nomad_token'] }}"
      method: POST
      url: http://127.0.0.1:4646/v1/job/acme-renew/periodic/force
    register: force_launch_output

  - name: List allocations for evaluation
    ansible.builtin.uri:
      follow_redirects: none
      force: true
      use_netrc: false
      use_proxy: false
      validate_certs: false
      return_content: true
      headers:
        X-Nomad-Token: "{{ ansible_facts['nomad_token'] }}"
      method: GET
      url: http://127.0.0.1:4646/v1/evaluation/{{ force_launch_output.json.EvalID }}/allocations
    register: evaluation_output

  - name: Wait for allocation to complete
    ansible.builtin.uri:
      follow_redirects: none
      force: true
      use_netrc: false
      use_proxy: false
      validate_certs: false
      return_content: true
      headers:
        X-Nomad-Token: "{{ ansible_facts['nomad_token'] }}"
      method: GET
      url: http://127.0.0.1:4646/v1/allocation/{{ evaluation_output.json[0].ID }}
    register: allocation_output
    until: allocation_output.json.ClientStatus == "complete"
    retries: 5
    delay: 2
