---
#
# Ansible implementation of Docker Engine on RHEL install guide
# https://docs.docker.com/engine/install/rhel/
#
- name: Remove old Docker packages
  ansible.builtin.dnf:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
      - podman
      - runc
    state: absent
    autoremove: true

- name: Install dnf-plugins-core
  ansible.builtin.dnf:
    name:
      - dnf-plugins-core
    state: present

- name: Remove legacy manually configured Docker repository
  ansible.builtin.yum_repository:
    name: docker-ce-stable
    state: absent

- name: Add Docker repository
  ansible.builtin.command:
    argv:
      - dnf
      - config-manager
      - --add-repo
      - https://download.docker.com/linux/rhel/docker-ce.repo
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker packages
  ansible.builtin.dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Enable and start Docker service
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: true

- name: Wait for Docker to be available
  ansible.builtin.wait_for:
    path: /var/run/docker.sock
    state: present
    timeout: 10

- name: Run Hello World image to validate Docker is working
  ansible.builtin.command:
    argv:
      - docker
      - run
      - --pull
      - always
      - --rm
      - --network
      - none
      - --read-only
      - --rm
      - hello-world
  changed_when: false
