---
name: ansible-lint
on:
  - push
jobs:
  ansible-lint:
    name: Ansible Lint
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: ansible-lint
        uses: ansible/ansible-lint@main

      - name: Download requirements from Ansible Galaxy
        run: ansible-galaxy collection install --requirements requirements.yml

      - name: Steampunk Spotter
        uses: xlab-steampunk/spotter-action@5.2.0
        env:
          SPOTTER_API_TOKEN: ${{ secrets.SPOTTER_API_TOKEN }}
        with:
          ansible_version: "2.18"
          profile: full
